### ISSUE TITLE
Don’t send push-messages for MUCs with disabled notifications 

### ISSUE THREAD

**Issue by dl8bh** [ChatSecure/ChatSecure-iOS#1030]
Hi, 
I just switched from ejabberd 18.03 to ejabberd 18.06. Good thing: Push now works reliable with ChatSecure. Annoying thing: now I get „New Message!“ notifications even for MUCs, for that I disabled notifications.

**Comment by tmolitor-stud-tu** [comment]
@dl8bh That's because your xmpp server and the appserver can not know which MUCs you did silence and which not.
That's an inherent problem caused by Apples push service which is seriously broken imho.

It can only be fixed by adding real time audio support to ChatSecure because Apple will only recognize ChatSecure as real time application if it can be used to make phone calls.
And only then Apple will allow ChatSecure to receive silent push notifications that don't trigger a "New Message!" notification.

**Comment by moppman** [comment]
> That's because your xmpp server and the appserver can not know which MUCs you did silence and which not.
Wait, why is there a "notifications" toggle for each MUC then? This is the issue I'm having. I disable notifications for a MUC and the button switches to on a couple of seconds later. This makes using larger MUCs with ChatSecure basically impossible.

**Comment by chrisballinger** [comment]
Ah sorry that's fixed in the master branch but hasn't been released yet.

**Comment by yannik995** [comment]
Currently I still get the "New Message!" push notifications, although the chat is set to silent.

Would it be possible to deactivate the "New Message!" push notification in settings?
you also get an additional notification after the Message content is known.

I agree @moppman, larger MUCs are unusable.
