### ISSUE TITLE
"Miscellaneous bad certificate"

### ISSUE THREAD

**Issue by lx-s** [ChatSecure/ChatSecure-iOS#1053]
10+ times a day, ChatSecure notifies me that 
> There was an error connecting to account ...@collapsar.de Please re-verify the server's certificate. "Miscellaneous bad certificate"

My server runs prosody 0.10.2 and uses Let's Encrypt for certificates ([xmpp.net c2s report](https://xmpp.net/result.php?domain=collapsar.de&type=client)). I am using ChatSecure 4.3.4 (134) on iOS 11.4.1. I looked through the server-logs as well as the prosody-debug output but I couldn't find anything that points me to it.

Do you have an ideas what could cause the constant bad-cert notifications? Can I provide you with more information that might help?

**Comment by jeifour** [comment]
The same thing (same error) happens to me when trying to login to my account on my university's Jabber server. Other clients are working, so the server doesn't seem to be at fault but "Miscellaneous bad certificate" doesn't really tell a lot about what ChatSecure doesn't like about it. Trying to get to the bottom of this.

**Comment by mimi89999** [comment]
Are you still experiencing this issue? I have made changes to domain checking in certificates in December.

**Comment by lx-s** [comment]
Ah, no. I haven't received them in the last weeks!

Thanks!

**Comment by mimi89999** [comment]
Probably fixed by https://github.com/ChatSecure/ChatSecure-iOS/commit/e46b17e24b7c2ab0cb33ca6916b8e0c2b1dc22f1

**Comment by zeusdice** [comment]
I am using ChatSecure 5.0.2 (167) on macOS Big Sur 11.1 and still can't connect to our company's jabber server.
```There was an error connecting to account... . Please re-verify the server's certificate. "Miscellaneous bad certificate"```
Other XMPP clients such as Spark, BeagleIM works well.
What's wrong?
But it works on my iPhone 11 Pro Max.
Please help me.
