### ISSUE TITLE
OMEMO key trust setting is not saved

### ISSUE THREAD

**Issue by sicherist** [ChatSecure/ChatSecure-iOS#1135]
Hello, I encountered the following problem in Chatsecure IOS version 4.3.8 (142)

My contact uses two devices for XMPP with OMEMO (Android Conversations and Linux Gajim). But he only receives my messages on one of the two devices . If he sends me a message from the other device I see the "something changed (...) compare codes" messages in Chatsecure and when I tap "compare codes" I can see that one of his omemo keys is "TOFU" but the switch on the other key is  disabled (grey). If I enable the switch to trust the key and tap "save", the setting is apparently not stored. If I go back to the "compare codes" setting, the key is disabled again.

**Comment by chrisballinger** [comment]
Does the other key say "Removed from Server"?

**Comment by sicherist** [comment]
No, it looks like this:
![IMG_20190720_203924](https://user-images.githubusercontent.com/6120865/61582840-250e8800-ab30-11e9-93e3-8a17d9cad8b3.jpg)

**Comment by chrisballinger** [comment]
Yikes, looks like we've got some layout issues for that localization. Can you translate that text for me?

**Comment by sicherist** [comment]
It says "OMEMO: 3 hours ago" "Not trustworthy device". Another problem with this screen is (at least here on my wives Iphone SE), if you tap the grey switch in portrait mode, the dialog opens asking what to do with the key (copy, save, mail, ect.) - just like if you tap on the key itself. I can only flip the switch in landscape mode.

**Comment by sicherist** [comment]
It might be the same Problem as this one: https://github.com/ChatSecure/ChatSecure-iOS/issues/1119

By the way the ""something changed..." message is not localized although the transifex website says "0 strings to translate".

**Comment by ichi-i** [comment]
I can replicate this issue (and the one referenced by @sicherist) too.

**Comment by milkywade** [comment]
I have the same issue.

**Comment by sicherist** [comment]
I can confirm that reinstalling chatsecure is a workaround.

**Comment by milkywade** [comment]
Well, I did that and now when I get a message from another contact, I get the push alert but when I open the Chatsecure application, I can not see the actual message: I can send messages fine but I won't see any messages received.
The server does not seem to be the issue as when I log in with the same account using gajim, I can see the messages.

**Comment by a11fruitless** [comment]
I am seeing this same issue as well. Reinstalling ChatSecure helped significantly. Except that changes your OMEMO key of course.

When I toggle the switches to change them from TOFU to Verified and save, when I open that screen back up everything is back to TOFU.

**Comment by chrisballinger** [comment]
Can you confirm that reinstalling fixes the issue permanently?

**Comment by milkywade** [comment]
It does not.

A and B use chatsecure on iOS. A also uses gajim. A sends a message from gajim to B. A also sends some messages to B using Chatsecure. Even if A and B accept all OMEMO keys from each other, B does no longer get any messages from B on chatsecure as the setting is not saved and Chatsecure keeps on saying that "something has changed". It's a bit of a nightmare really.

**Comment by chrisballinger** [comment]
I was able to reproduce this issue. It was likely caused by a regression in the XLForm library 4.0.1 update: https://github.com/xmartlabs/XLForm/issues/1052

Looking into mitigations.

**Comment by chrisballinger** [comment]
I merged a patch that fixes the issue, and submitted a hotfix build 4.3.9 to Apple.

If you haven't already, please consider joining the TestFlight beta group: https://testflight.apple.com/join/psrh8VB6

Cheers!

**Comment by milkywade** [comment]
Hi - I updated both Bob and Alice's phones to 4.3.9. Alice's phone does not have an issue anymore. However Bob's phone is still not able to save all keys (see screenshot attached). iOS on both devices is 12.4. Bob can save them but when the application is started anew again, they appear as unsaved.

![cles_](https://user-images.githubusercontent.com/43685172/62983063-07c69400-be26-11e9-956c-d45ec5c7df66.jpg)
