### ISSUE TITLE
Unavailable in France / French App Store

### ISSUE THREAD

**Issue by guill4ume** [ChatSecure/ChatSecure-iOS#127]
Hello !
Did not found my answer, so i ask :

An Iphone-user friend of mine is trying to download the app from french Itunes.
As it's on US Itunes, it can't be downloaded.

Is there a way to download the .ipa elsewhere ?
To build it by myself ?

Thanks in advance ;)

**Comment by hurlebouc** [comment]
Is it possible to give you some help to fix this problem?

**Comment by Kcchouette** [comment]
Hi,

Today, a new document replace the older (2007). You can find it here: http://legifrance.gouv.fr/jo_pdf.do?cidTexte=JORFTEXT000030255024

Ask if you want some help :)

Thanks

**Comment by Sigmun** [comment]
Any updates on this issue ?

**Comment by desaparecido** [comment]
up - we need 2015 informations about this issue please.

**Comment by chrisballinger** [comment]
Still working on this... sorry!

**Comment by KiNGVirusPL** [comment]
I really need this application for business, if you need any help translating anything for the french store, contact me on jabber: virus@jabber.se. Thanks. If you need a donation to push it faster, then ask me ;)

**Comment by chrisballinger** [comment]
It's mainly limited by two things:

1) We need someone who can read/write French and (preferably) is also a
lawyer who understands tech
2) We need to physically get these forms in triplicate to some government
office in France

If you can recommend anyone, please let me know. Thank you!

**Comment by KiNGVirusPL** [comment]
Add me on jabber

**Comment by guillaume-uH57J9** [comment]
I contributed $15 to bountysource https://www.bountysource.com/issues/4520550-unavailable-in-france-french-app-store

**Comment by sypianski** [comment]
Has any progress been made on this issue? I can translate some French if you want.

**Comment by davidlatapie** [comment]
And I might help for the legal part.

**Comment by Guilz** [comment]
Hello there,
Can we have an update on this issue? That would indeed be super nice to have ChatSecure in the French App Store, and I am also looking forward to it.

**Comment by matunixe** [comment]
As other guys said it would be good to make the installation of chat secure available in France.

**Comment by adrien-n** [comment]
Hi,

I'm very interested in seeing this move forward so I intend to work on it and get all the things readied so you only have a few trivial steps left (basically providing names and the likes).

One thing I'd like to know however is if the publication to the App Store will be done as a company or as an individual.

**Comment by chrisballinger** [comment]
Thanks @adrien-n! Would you mind emailing me directly?

**Comment by Sigmun** [comment]
Any updates on that issue ?

**Comment by chrisballinger** [comment]
Progress update: we are getting closer to finishing and submitting the required docs to ANSSI.

**Comment by guillaume-uH57J9** [comment]
Hooray ! Thanks @chrisballinger and @adrien-n for bringing ChatSecure to iOS, don't forget to claim the bounty once it's done.

**Comment by llbstr** [comment]
Merci beaucoup, it's really appreciated **: )**

**Comment by thundergreen** [comment]
Just for my understanding.. Does it mean chatsecure will be available in
France soon?
Would be awesome


Am 07.03.2017 19:08 schrieb "llbstr" <notifications@github.com>:

Merci beaucoup, it's really appreciated *: )*

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ChatSecure/ChatSecure-iOS/issues/127#issuecomment-284806544>,
or mute the thread

**Comment by chrisballinger** [comment]
Will be submitting the docs soon. Not sure how long it will take to get the response on ANSSI. I'll post updates here when I hear anything.

**Comment by thundergreen** [comment]
Thanks a lot. I think a lot of people will be happy to get chatsecure in
France. There's no other way to get it on my phone? I'm totally new to
chatsecure

Am 07.03.2017 20:09 schrieb "Chris Ballinger" <notifications@github.com>:

**Comment by chrisballinger** [comment]
Just sent the paperwork to ANSSI.

**Comment by guillaume-uH57J9** [comment]
The administrative hurdle for crypto-system in France was just covered in the following in this online article (french). This very issue of ChatSecure on iOS was cited as an example https://www.nextinpact.com/news/103575-les-outils-chiffrement-face-a-declaration-a-anssi-exception-francaise.htm

N.B. there's a paywall, but I am a subscriber and can send you links to read it for free, just contact me at riy7vqmkcn685y3@jetable.org

**Comment by chrisballinger** [comment]
Just received approval from Apple. 

Next update will be available in France! 🇫🇷

**Comment by llbstr** [comment]
Thanks!

**Comment by thundergreen** [comment]
Awesome! I just changed my market to German so it worked but congrats my
friend. French market is open

Am 26.04.2017 17:54 schrieb "llbstr" <notifications@github.com>:

**Comment by Sigmun** [comment]
Bravo!

**Comment by CyberJinh** [comment]
any cydia repo for the app are available ?

**Comment by chrisballinger** [comment]
Don't use a Cydia version.

It should be available on the App Store within the next week or so.

**Comment by adrien-n** [comment]
Aaaaannnd..... it's available. :)

**Comment by llbstr** [comment]
Thanks! Tried it and magic happened : )

**Comment by chrisballinger** [comment]
Yayyy

**Comment by Sigmun** [comment]
Installed ! Merci !

**Comment by guillaume-uH57J9** [comment]
@chrisballinger there is an unclaimed $80 bounty for this issue, you can claim it there since it was resolved https://www.bountysource.com/issues/4520550-unavailable-in-france-french-app-store

I made a contribution to the bounty, and would prefer the bounty go toward ChatSecure contributors, rather than expire and get eat by BountySource.

**Comment by chrisballinger** [comment]
@guillaume-uH57J9  Thanks for the reminder! I think I tried to claim it before but was rejected by someone.

**Comment by meaz** [comment]
I've read there https://monal.im/blog/omemo-and-french-laws/ that it is still not available in France. ANy news about that?

**Comment by guillaume-uH57J9** [comment]
@meaz I was able to install ChatSecure on an iOS device after the appropriate paperwork was filled with French authorities

The article refers to Monal.im, a different OMEMO client who excluded french users rather than fill paperwork. For news about this, you should contact Monal.im developers

**Comment by meaz** [comment]
Yeah sorry, I posted in the wrong place!
